# Dataset Overview

This notebook explores the dataset by printing counts of request, tracking-related requests etc.

## Setup and data load

In [2]:
import pandas as pd
import seaborn as sns
from utils import parse_har_files_to_dataframe
from common import BASE_HAR_DIR


sns.set_theme(style="whitegrid", context="paper")
pd.set_option('display.max_colwidth', 128)

df = parse_har_files_to_dataframe(BASE_HAR_DIR, test=False, use_cache=True)

## Dataset summary

In [3]:
print(f'Number of requests: {len(df)}')
print(f'Number of third-party requests: {len(df[df.third_party])}')
print(f'Number of tracking-related requests: {len(df[df.is_tracker])}')
print(f'Number of countries: {df.country.nunique()}')
print(f'Number of unique websites: {df.site_domain.nunique()}')
print(f'Number of unique request domains: {df.req_domain.nunique()}')
print(f'Number of unique CNAME domains: {df.cname.nunique()}')

Number of requests: 242967
Number of third-party requests: 107586
Number of tracking-related requests: 55856
Number of countries: 5
Number of unique websites: 50
Number of unique request domains: 455
Number of unique CNAME domains: 324

### No of requests by exp mode

In [4]:
df.exp_mode.value_counts().to_frame()

           count
exp_mode
tracking  124416
social    118551

### No of requests by consent mode

In [6]:
df.consent_mode.value_counts().to_frame()

               count
consent_mode
Accept        136206
Reject        106761

In [7]:
df[df.third_party & (df.entity != '')].entity.value_counts().head(10).to_frame()

               count
entity
Google         27741
Microsoft       4844
Stripe          3967
Facebook        3159
Usercentrics    2963
Doofinder       2035
PayPal          1887
Trusted Shops   1792
Zendesk         1463
Virtual Minds   1437

### No of websites by consent, country and exp_mode

In [8]:
df.groupby(['exp_mode', 'consent_mode', 'country'])['site_domain'].\
    nunique().to_frame()

                               site_domain
exp_mode consent_mode country
social   Accept       DE                10
                      ES                10
                      FR                10
                      IT                10
                      NL                10
         Reject       DE                10
                      ES                10
                      FR                10
                      IT                10
                      NL                10
tracking Accept       DE                10
                      ES                10
                      FR                10
                      IT                10
                      NL                10
         Reject       DE                10
                      ES                10
                      FR                10
                      IT                10
                      NL                10

### No of requests by consent, country, exp_mode, third-partyness, and website

In [9]:
df['third_party'].value_counts().to_frame()

              count
third_party
False        135381
True         107586

In [10]:
df.country.value_counts().to_frame()

         count
country
IT       73084
ES       51863
DE       43931
FR       41896
NL       32193

In [11]:
df.groupby(['exp_mode', 'consent_mode', 'country']).\
    site_domain.value_counts().to_frame()

                                                        count
exp_mode consent_mode country site_domain
social   Accept       DE      sanicare.de                1836
                              medikamente-per-klick.de   1600
                              apotal.de                  1511
                              shop-apotheke.com          1347
                              aponeo.de                  1260
...                                                       ...
tracking Reject       NL      gezondheidaanhuis.nl        438
                              koopjesdrogisterij.nl       325
                              deonlinedrogist.nl          294
                              trekpleister.nl             269
                              kruidvat.nl                 242

[200 rows x 1 columns]

In [12]:
df.is_tracker.value_counts().to_frame()

             count
is_tracker
False       187111
True         55856

In [13]:
df.is_cname_tracker.value_counts().to_frame()

                   count
is_cname_tracker
False             231467
True               11500